### PR TITLE
Atlas

### PR DESCRIPTION
**Pull request by Experiment5X**
This commit adds a feature into Assembly for searching for tags, it's pretty self explanatory.

Ignore the control in the middle of the title bar of the search window, I'm running windows 10 in a VM and VMWare puts that on all the windows.

### CODE REVIEW

**Comment by ThunderWaffle** [comment]
Can you revert your changes to XBDMCommunicator.csproj?  We probably don't want to change how it goes about finding xdevkit.  @Lord-Zedd or @adierking should take a look too.

**Comment by adierking** [comment]
>Can you revert your changes to XBDMCommunicator.csproj? We probably don't want to change how it goes about finding xdevkit. @Lord-Zedd or @adierking should take a look too.

Yeah, the intent here is for you to drop xdevkit.dll into the XBDMCommunicator folder. We don't want to hardcode any system-specific paths into the project files. Fix this and then everything should be good IMO.

**Comment by 0xdeafcafe** [comment]
One other thing, this change is on the `atlas` branch, but it's applying changes and adding the tag searcher to the assembly project. It should really be moved into the `dev` branch.

**Comment by Experiment5X** [comment]
I can't compile the dev branch because I don't have the gplex or gppg executables and even if I did it looks like gppg needs the file LispScriptParser.y which isn't in the repo either. I get this as the output when I try and compile Blamite: 

C:\Users\Adam\Developer\Assembly\src\Blamite\Blamite.csproj(566,5): error MSB3073: The command "Blam\Scripting\Analysis\Executables\gppg.exe /gplex /out:Blam\Scripting\Analysis\LispScriptParser.cs Blam\Scripting\Analysis\LispScriptParser.y" exited with code 3.

I'm using Visual Studio 2015 if that would make any difference. I can compile the atlas branch just fine though which is why I put the changes on there. After I undo the xdevkit.dll stuff should I keep the changes on atlas or is there a simple fix for this? 

I didn't even notice the other project in there with the changed UI. That looks really nice. The organization of the tags is much better I think.

**Comment by adierking** [comment]
Should be fixed now...apparently VS builds have been broken for a while now and no one even noticed. Ugh. Sorry about that.

**Comment by Experiment5X** [comment]
I made another pull request with the changes on dev [here](https://github.com/XboxChaos/Assembly/pull/182).

**Comment by kornman00** [comment]
@Experiment5X that control in the middle of the title bar has nothing to do with VMware http://stackoverflow.com/questions/36727482/how-to-remove-the-go-to-live-visual-tree-enable-selection-display-layou

**Pull request closed without merging**
